- builder:
    name: zuul-dev-install
    builders:
      - shell: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev


- job:
    name: a10-project-config-master
    node: bare-trusty

    scm:
        - scm-a10-project-config

    builders:
        - zuul-dev-install
        - revoke-sudo
        - tox:
            envlist: 'pep8,jjb,jenkins-project,zuul'

    publishers:
        - console-log

    triggers:
        - sqs

- job:
    name: a10-project-config-pulls
    node: bare-trusty

    scm:
        - scm-a10-project-config

    builders:
        - zuul-dev-install
        - revoke-sudo
        - tox:
            envlist: 'pep8,jjb,jenkins-project,zuul'

    publishers:
        - console-log

    triggers:
        - github-pull-request-all
