- builder:
    name: zuul-dev-install
    builders:
      - shell: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev

- job:
    name: a10-project-config
    node: bare-trusty

    properties:
      - github:
          url: https://github.com/a10networks-ci/project-config

    scm:
      - git:
         url: https://github.com/a10networks-ci/project-config.git

    builders:
        - zuul-dev-install
        - revoke-sudo
        - tox:
            envlist: 'pep8,jjb,jenkins-project,zuul'

    publishers:
        - console-log

    triggers:
        - github
        - github-pull-requests
