- builder:
    name: install-zuul-dev-libs
    builders:
      - shell: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev

- job-template:
    name: 'a10-project-config-{which}'
    node: bare-trusty

    properties:
        - github:
            url: '{github-url}'

    scm:
        - git:
            url: '{github-url}.git'
            refspec: '{refspec}'
            branches: '{branches}'

    builders:
        - install-zuul-dev-libs
        - revoke-sudo
        - tox:
            envlist: 'pep8,jjb,jenkins-project,zuul'

    publishers:
        - console-log

    triggers:
        - '{trigger}'
