
- job-template:
    name: a10-project-config-master
    node: slave-project-config
    concurrent: false

    properties:
        - github:
            url: '{github-url}'

    scm:
        - git:
            url: '{github-url}.git'
            skip-tag: true

    builders:
        - shell:
            #!/bin/sh
            tox -e pep8,jjb,jenkins-project,zuul

    publishers:
        - console-log

    triggers:
        - github

- job-template:
    name: a10-project-config-pulls
    node: slave-project-config

    properties:
        - github:
            url: '{github-url}'

    scm:
        - git:
            url: '{github-url}.git'
            skip-tag: true
            refspec: '+refs/pull/*:refs/remotes/origin/pr/*'
            branches:
                - '${{sha1}}'

    builders:
        - shell:
            #!/bin/sh
            tox -e pep8,jjb,jenkins-project,zuul

    publishers:
        - console-log

    triggers:
        - github-pull-requests
