- builder:
    name: install-zuul-dev-libs
    builders:
      - shell: |
          sudo apt-get -y update
          sudo apt-get -y install -y libjpeg-dev zlib1g-dev

- job-template:
    name: a10-project-config-master
    node: bare-trusty

    properties:
        - github:
            url: '{github-url}'

    scm:
        - git:
            credentials-id: '6188d1d6-bfb6-42f2-994b-645db349f8f9'
            url: '{github-url}.git'
            skip-tag: true
            # refspec: '+refs/heads/*:refs/remotes/origin/*'
            # branches:
            #     - '{branch-specifier}'

    builders:
        - install-zuul-dev-libs
        - revoke-sudo
        - tox:
            envlist: 'pep8,jjb,jenkins-project,zuul'

    publishers:
        - console-log

    triggers:
        - github

- job-template:
    name: a10-project-config-pulls
    node: bare-trusty

    properties:
        - github:
            url: '{github-url}'

    scm:
        - git:
            credentials-id: '6188d1d6-bfb6-42f2-994b-645db349f8f9'
            url: '{github-url}.git'
            skip-tag: true
            refspec: '+refs/pull/*:refs/remotes/origin/pr/*'
            branches:
                - '${{sha1}}'

    builders:
        - install-zuul-dev-libs
        - revoke-sudo
        - tox:
            envlist: 'pep8,jjb,jenkins-project,zuul'

    publishers:
        - console-log

    triggers:
        - github-pull-requests
