- builder:
    name: zuul-dev-install
    builders:
      - shell: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev

- job-template:
    name: 'a10-project-config-{which}'
    node: bare-trusty

    scm:
        - '{src}'

    builders:
        - zuul-dev-install
        - revoke-sudo
        - tox:
            envlist: 'pep8,jjb,jenkins-project,zuul'

    publishers:
        - console-log

    triggers:
        - '{trig}'
