- job:
    name: a10-project-config-master
    node: bare-trusty

    scm:
        - scm-a10-project-config

    builders:
        - revoke-sudo
        - tox:
            envlist: 'pep8,jjb,jenkins-project,zuul'

    publishers:
        - console-log

    triggers:
        - sqs

- job:
    name: a10-project-config-pulls
    node: bare-trusty

    scm:
        - scm-a10-project-config

    builders:
        - revoke-sudo
        - tox:
            envlist: 'pep8,jjb,jenkins-project,zuul'

    publishers:
        - console-log

    triggers:
        - github-pull-request-all
